### PR TITLE
bugfix - revert years emdat to original so that extra years don't bre…

### LINKED ISSUE #7: bug introduced in emdat wrangling
Original PR handled emdat data correctly:

https://github.com/OCHA-DAP/ds-aa-afg-drought/blob/908cbcb85ffee24f7c03d2d2453ea4179a20fd76/exploration/04_trigger_exploration.R#L397-L402

At some point in PR this was changed incorrectly and never fixed to:

https://github.com/OCHA-DAP/ds-aa-afg-drought/blob/d795a03590188477995f34dfc10ebf992b8c24a7/exploration/04_trigger_exploration.R#L435-L440

my guess is that someone was playing/experimenting w/ code on branch with the data during the PR and forgot to change it back

https://github.com/OCHA-DAP/ds-aa-afg-drought/pull/6#discussion_r1841261057

### PR DESCRIPTION
**Pull request by zackarno**
somewhere in addressing comments in original trigger exploration code the emdat years were modified in such a way that does not allow code to run - shown in this issue: https://github.com/OCHA-DAP/ds-aa-afg-drought/issues/7

PR closes #7

### CODE REVIEW

File: exploration/04_trigger_exploration.R [hunk 1]
```diff
@@ -400,84 +400,84 @@ df_chirps_wy_2000 <- df_chirps |>
...
     month,
     year
   )
 
-df_emdat_wy <- df_emdat |> 
+df_emdat_wy <- df_emdat |>
   dplyr$transmute(
     indicator = "EMDAT",
-    year = c(2000, 2001, 2002, 2007, 2008, 2011, 2018, 2019, 2021, 2022, 2023),
+    year = c(2001, 2007, 2008, 2011, 2018, 2023),
```
Comment (zackarno) [inline exploration/04_trigger_exploration.R:438]: this years are basically taken from the start_year & end_year, but it looks like there was a bit of interpretation and perhaps country-level inputs?

**Comment by zackarno** [comment]
The only change is the one highlighted in https://github.com/OCHA-DAP/ds-aa-afg-drought/pull/8/files#r1844338197

The rest is just linting from pre-commit plus I deleted my .python_version file from tracking
